# Your data frame

In [1]:
import os
import pandas as pd
import json

# Definimos la ruta donde se encuentran los archivos JSON
ruta_json = './output_json/'

# Inicializamos una lista para almacenar los DataFrames de cada archivo JSON
dataframes = []

# Iteramos sobre cada archivo en la ruta
for archivo in os.listdir(ruta_json):
    # Verificamos que sea un archivo JSON
    if archivo.endswith('.json'):
        # Leemos el archivo JSON y convertimos los datos en un diccionario de Python
        with open(os.path.join(ruta_json, archivo)) as f:
            data = json.load(f)
            docs = data['documents']
            docs.pop('facets', None)  # Ignoramos la propiedad "facets" dentro de "documents"
        
        # Creamos un DataFrame con los datos del archivo JSON y lo agregamos a la lista
        df = pd.DataFrame.from_dict(docs, orient='index')
        dataframes.append(df)

# Combinamos todos los DataFrames en uno solo
df_combinado = pd.concat(dataframes)

# Reiniciamos los índices del DataFrame combinado
# df_combinado.reset_index(drop=True, inplace=True)

# Mostramos el DataFrame combinado
# print(df_combinado)
# Guardar el DataFrame combinado como un archivo Excel
ruta_salida_excel = 'data.csv'
df_combinado.to_csv(ruta_salida_excel, index=False)

In [2]:
df_combinado

,id,last_modified_date,admreg,admreg_key,authors,count,count_key,docna,docty,docty_key,...,no_of_pages,sectr,sectr_key,majtheme,EnvironmentalCategory,credit_no,colti,ml_abstracts,alt_title,src_cit
D34112367,34112367,2023-07-05T00:00:00Z,"South Asia,South Asia","119231,119231",{'0': {'author': 'World Bank'}},Afghanistan,82662,{'0': {'docna': 'Afghanistan - Water Emergency...,Project Appraisal Document,540656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D33836479,33836479,2022-06-06T00:00:00Z,"South Asia,South Asia","119231,119231",NaN,Afghanistan,82662,{'0': {'docna': 'Afghanistan - Emergency Food ...,Project Appraisal Document,540656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D33841647,33841647,2022-06-13T00:00:00Z,"South Asia,South Asia","119231,119231",{'0': {'author': 'World Bank'}},Afghanistan,82662,{'0': {'docna': 'Afghanistan – Health Emergenc...,Project Appraisal Document,540656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D33813174,33813174,2022-05-10T00:00:00Z,"South Asia,South Asia","119231,119231",{'0': {'author': 'World Bank'}},Afghanistan,82662,{'0': {'docna': 'Afghanistan Community Resilie...,Project Appraisal Document,540656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D32791172,32791172,NaN,"South Asia,South Asia","119231,119231",NaN,Afghanistan,82662,"{'0': {'docna': 'Afghanistan - Early Warning, ...",Project Appraisal Document,540656,...,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D19457542,19457542,NaN,"Africa,Africa","119222,119222",NaN,Zimbabwe,82703,{'0': {'docna': 'Zimbabwe - Hwange-Sanyati Bio...,Project Appraisal Document,540656,...,86,"{'0': {'sector': 'Public Administration'}, '1'...","369163,369180",Environment and natural resource management,B,NaN,NaN,NaN,NaN,NaN
D440259,440259,NaN,"Africa,Africa","119222,119222",NaN,Zimbabwe,82703,{'0': {'docna': 'Zimbabwe - Land Reform Suppor...,Project Appraisal Document,540656,...,49,"{'0': {'sector': 'Agriculture, Fishing and For...",369180,NaN,NaN,3286,NaN,NaN,NaN,NaN
D693587,693587,NaN,"Africa,Africa","119222,119222",NaN,Zimbabwe,82703,{'0': {'docna': 'Zimbabwe - Agricultural Servi...,Project Appraisal Document,540656,...,42,"{'0': {'sector': 'Agriculture, Fishing and For...",369180,NaN,NaN,3080,"World Development Sources, WDS 1998-2",NaN,NaN,NaN
D442213,442213,NaN,"Africa,Africa","119222,119222",NaN,Zimbabwe,82703,{'0': {'docna': 'Zimbabwe - Park Rehabilitatio...,Project Appraisal Document,540656,...,97,{'0': {'sector': '(Historic)Environment'}},369178,NaN,NaN,3083,"World Development Sources, WDS 1998-3",NaN,NaN,NaN
D440574,440574,NaN,"Africa,Africa","119222,119222",NaN,Zimbabwe,82703,{'0': {'docna': 'Zimbabwe - Community Action P...,Project Appraisal Document,540656,...,67,{'0': {'sector': '(Historic)Urban Development'}},369177,NaN,NaN,3072,"World Development Sources, WDS 1998-3",NaN,NaN,NaN

In [6]:
ruta_salida_csv = './boards/data.csv'
df_combinado.to_csv(ruta_salida_csv, index=False)

In [10]:
import openpyxl
ruta_salida_excel = './boards/data.xlsx'
df_combinado.to_excel(ruta_salida_excel, index=False, engine='openpyxl')

 ## Esta es la cantidad de errores que pasaran como el último, digamos un documento tiene uno o más ids

In [34]:
repnb = df_combinado['repnb']

values_null = repnb.isna()

# print('\n',repnb)
print(values_null)
values_null.sum()

D34112367    False
D33836479    False
D33841647    False
D33813174    False
D32791172    False
             ...
D19457542    False
D440259      False
D693587      False
D442213      False
D440574      False
Name: repnb, Length: 5906, dtype: bool

9